name: Java CI with Gradle

on:
  schedule:
    - cron: '30 12 * * 3'  # Every Wednesday at 12:30 UTC
    - cron: '0 22 * * 5'   # Every Friday at 22:00 UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17.0.0+35, 16.0.2+7, 11.0.21+9]
    steps:
    - uses: actions/checkout@v3
    - name: Set executable permissions for Gradle Wrapper
      run: chmod +x ./gradlew
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
